# encoding: utf-8

default:
  session_key: '_diavelforum_de_mm_session'

  forum_name: Diavelforum.de
  forum_url: http://diavelforum.de

  sessions:
    force_confirmation: true
    confirmation_text: >
      Mir ist bewusst, dass diese Mitgliederkarte ein unabhängiges Projekt ist und meine
      eingegeben Daten nicht im diavelforum.de sondern in einem eigenständigen System
      gespeichert werden. Ich habe die <a href="/privacy">Hinweise zum Datenschutz</a> gelesen.

  vbulletin:
    base_url: http://diavelforum.de

  map:
    default_lat: 49.167339
    default_lng: 9.645996
    default_zoom: 6

  static_pages:
    legal_info:
      content: >
        Bla bla <strong>foo bar</strong>
    privacy:
      content: >
        Bla bla <strong>foo bar</strong>